// backend/config/env.ts
// Validate and export environment variables

interface EnvConfig {
  PORT: number;
  NODE_ENV: 'development' | 'production' | 'test';
  GEMINI_API_KEY: string;
  SUPABASE_URL: string;
  SUPABASE_KEY: string;
  SUPABASE_JWT_SECRET: string;
  JWT_EXPIRY: string;
  MAX_FILE_SIZE_MB: number;
  MAX_CHAT_HISTORY_MESSAGES: number;
  GEMINI_MAX_TOKENS: number;
  RATE_LIMIT_WINDOW_MS: number;
  RATE_LIMIT_MAX_REQUESTS: number;
}

const requiredEnvVars = [
  'GEMINI_API_KEY',
  'SUPABASE_URL',
  'SUPABASE_KEY',
  'SUPABASE_JWT_SECRET',
];

requiredEnvVars.forEach((envVar) => {
  if (!process.env[envVar]) {
    console.error(`❌ Missing required environment variable: ${envVar}`);
    process.exit(1);
  }
});

export const config: EnvConfig = {
  PORT: parseInt(process.env.PORT || '5000', 10),
  NODE_ENV: (process.env.NODE_ENV || 'development') as EnvConfig['NODE_ENV'],
  GEMINI_API_KEY: process.env.GEMINI_API_KEY!,
  SUPABASE_URL: process.env.SUPABASE_URL!,
  SUPABASE_KEY: process.env.SUPABASE_KEY!,
  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET!,
  JWT_EXPIRY: process.env.JWT_EXPIRY || '7d',
  MAX_FILE_SIZE_MB: parseInt(process.env.MAX_FILE_SIZE_MB || '5', 10),
  MAX_CHAT_HISTORY_MESSAGES: parseInt(process.env.MAX_CHAT_HISTORY_MESSAGES || '50', 10),
  GEMINI_MAX_TOKENS: parseInt(process.env.GEMINI_MAX_TOKENS || '2048', 10),
  RATE_LIMIT_WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000', 10),
  RATE_LIMIT_MAX_REQUESTS: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS || '30', 10),
};

export const MEDICAL_DISCLAIMERS = {
  chat: `⚠️ IMPORTANT MEDICAL DISCLAIMER:
This AI assistant provides general health information for educational purposes only.
It is NOT a substitute for professional medical advice, diagnosis, or treatment.
Always consult with a qualified healthcare provider for medical concerns.
Do not use this system for emergencies - call emergency services immediately.`,

  report: `⚠️ This analysis is AI-generated and not a substitution for professional medical interpretation.
Results should be reviewed by a qualified healthcare provider.`,

  risk: `⚠️ This risk assessment is generated by AI and should NOT be used for diagnosis.
Seek immediate medical attention if experiencing emergency symptoms.`
};

export const MEDICAL_LAB_RANGES = {
  'blood_glucose': { min: 70, max: 100, unit: 'mg/dL', name: 'Fasting Blood Glucose' },
  'systolic_bp': { min: 90, max: 120, unit: 'mmHg', name: 'Systolic Blood Pressure' },
  'diastolic_bp': { min: 60, max: 80, unit: 'mmHg', name: 'Diastolic Blood Pressure' },
  'heart_rate': { min: 60, max: 100, unit: 'bpm', name: 'Heart Rate' },
  'oxygen_saturation': { min: 95, max: 100, unit: '%', name: 'Oxygen Saturation (SpO2)' },
  'hemoglobin': { min: 12, max: 17.5, unit: 'g/dL', name: 'Hemoglobin' },
  'cholesterol_total': { min: 0, max: 200, unit: 'mg/dL', name: 'Total Cholesterol' },
  'triglycerides': { min: 0, max: 150, unit: 'mg/dL', name: 'Triglycerides' },
  'ldl': { min: 0, max: 100, unit: 'mg/dL', name: 'LDL Cholesterol' },
  'hdl': { min: 40, max: 300, unit: 'mg/dL', name: 'HDL Cholesterol' },
  'creatinine': { min: 0.7, max: 1.3, unit: 'mg/dL', name: 'Creatinine' },
  'bmi': { min: 18.5, max: 25, unit: 'kg/m²', name: 'Body Mass Index' },
};
